export interface Ticket {
  id: string;
  customerName: string;
  customerEmail: string;
  company: string;
  tier: 'Free' | 'SME' | 'Enterprise';
  subject: string;
  description: string;
  createdAt: string;
  status: 'Open' | 'In Progress' | 'Resolved' | 'Escalated';
  sentiment: 'Frustrated' | 'Neutral' | 'Anxious' | 'Calm';
  logs: string[];
  environment: string;
  assignedTier?: 1 | 2 | 3;
  agentNotes?: string;
  agentResponse?: string;
  handoverSummary?: HandoverSummary;
}

export interface HandoverSummary {
  ticketId: string;
  customerImpact: string;
  defectSummary: string;
  troubleshootingPerformed: string[];
  rootCauseHypothesis: string;
  environmentSpecs: string;
  nextSteps: string;
}

export interface KBArticle {
  id: string;
  title: string;
  category: 'General' | 'Technical' | 'Known Error';
  content: string;
  steps?: string[];
}

export interface AgentAnalysisResponse {
  assignedTier: 1 | 2 | 3;
  sentiment: 'Frustrated' | 'Neutral' | 'Anxious' | 'Calm';
  agentNotes: string;
  agentResponse?: string;
  handoverSummary?: HandoverSummary;
}

export interface ProjectFile {
  path: string;
  content: string;
  size?: number;
}

export interface ProjectAnalysisResult {
  projectName: string;
  techStack: string[];
  totalFiles: number;
  linesOfCodeEstimated: number;
  architectureOverview: string;
  securityAudit: {
    severity: 'High' | 'Medium' | 'Low' | 'Clean';
    vulnerabilities: string[];
  };
  bugsAndRisks: {
    tier: 1 | 2 | 3;
    title: string;
    description: string;
    affectedFiles: string[];
    fixRecommendation: string;
  }[];
  performanceOptimizations: string[];
  autoGeneratedKEDB: {
    title: string;
    category: 'General' | 'Technical' | 'Known Error';
    content: string;
    steps: string[];
  }[];
}

export type NavTab = 'inbox' | 'queue' | 'kedb' | 'ingress' | 'settings' | 'project';

